# Generated by Django 4.0.1 on 2022-01-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macaroonApp', '0004_profile_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='customGroups', to='macaroonApp.Profile')),
            ],
        ),
    ]
