# Generated by Django 4.0.1 on 2022-01-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macaroonApp', '0006_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver',
            new_name='intermediary',
        ),
    ]
