# Generated by Django 4.0.1 on 2022-01-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macaroonApp', '0009_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('moneyReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediary_received', to='macaroonApp.profile')),
                ('moneySender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_created', to='macaroonApp.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
