# Generated by Django 4.0.1 on 2022-01-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macaroonApp', '0010_finalpayment_delete_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='contract_address',
        ),
    ]
